In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv
from sklearn.metrics import roc_curve, auc
import statistics
from sklearn.metrics import roc_curve, auc, accuracy_score, roc_auc_score
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import balanced_accuracy_score,roc_auc_score
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import GradientBoostingClassifier

import statistics

import pandas as pd
import numpy as np
from scipy.optimize import minimize
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss
import os

In [6]:
list_of_items = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]

datasets_names= list()
list_mean_test_errors =  list()
list_mean_train_errors =  list()
list_mean_validation_errors =  list()
all_rankings= list()

for data_set in list_of_items:
    
    #for item in list_of_items:
    file = open("results_BestVal_multiclass_dataset_{}.txt".format(data_set),"r")
    file_content = file.readlines()

    string =file_content[-3]
    
    vowels = ''
    for i in vowels:
        string = string.replace(i, '')

    res = eval(string)

    list_of_validation_errors =  list()
    list_of_test_errors =  list()

    for i in res:
        _, _, validation_error, test_error = i

        list_of_validation_errors.append(validation_error)
        list_of_test_errors.append(test_error)
           
    mean_val_error = statistics.mean(list_of_validation_errors)
    sdev_val = statistics.stdev(list_of_validation_errors)
    
    mean_test_error = statistics.mean(list_of_test_errors)
    sdev_test = statistics.stdev(list_of_test_errors)

    datasets_names.append(data_set)

    list_mean_validation_errors.append(mean_val_error)
    list_mean_test_errors.append(mean_test_error)

In [9]:
data_results = pd.DataFrame(list(zip(datasets_names,list_mean_validation_errors,list_mean_test_errors)), 
               columns =['dataset_id', 'validation_error', 'test_error'])

In [10]:
data_results

    dataset_id  validation_error  test_error
0            1          0.208765    0.243665
1            2          0.358068    0.371167
2            3          0.414934    0.416793
3            4          0.408783    0.438790
4            5          0.440949    0.424148
5            6          0.131037    0.141985
6            7          0.165010    0.187086
7            8          0.196952    0.212170
8            9          0.194089    0.199301
9           10          0.188798    0.184612
10          11          0.503056    0.537271
11          12          0.506752    0.535923
12          13          0.511555    0.537319
13          14          0.518415    0.553038
14          15          0.402670    0.412418
15          16          0.379654    0.468079
16          17          0.419381    0.494368
17          18          0.395696    0.457027