In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv
from sklearn.metrics import roc_curve, auc
import statistics
from sklearn.metrics import roc_curve, auc, accuracy_score, roc_auc_score
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import balanced_accuracy_score,roc_auc_score
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import GradientBoostingClassifier

import statistics

import pandas as pd
import numpy as np
from scipy.optimize import minimize
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss
import os

In [2]:
ETs = [900, 3600, 9000]
list_of_items = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]

datasets_names= list()

data_frame =  pd.DataFrame()
data_frame['dataset_id'] =  list_of_items

for et in ETs:    

    list_mean_test_errors =  list()
    
    for data_set in list_of_items:    

        file = open("results_AutoSklearn_multiclass_dataset_{}-{}.txt".format(et, data_set),"r")
        file_content = file.readlines()

        string = file_content[-1]

        string_to_remove= 'Log_loss score '
        string_ = string.replace(string_to_remove, '')

        test_error = float(string_)

        list_mean_test_errors.append(test_error)    
        datasets_names.append(data_set)
        
    data_frame['AutoSkl_{}'.format(et)] = list(list_mean_test_errors)

data_frame

    dataset_id  AutoSkl_900  AutoSkl_3600  AutoSkl_9000
0            1     0.229391      0.225197      0.222522
1            2     0.360272      0.345823      0.348048
2            3     0.397571      0.389191      0.390969
3            4     0.438411      0.429461      0.420021
4            5     0.499343      0.453517      0.452514
5            6     0.116972      0.114202      0.115884
6            7     0.162577      0.164280      0.168936
7            8     0.193382      0.192112      0.197157
8            9     0.195395      0.182074      0.181556
9           10     0.217578      0.196550      0.204323
10          11     0.501951      0.500283      0.502515
11          12     0.515868      0.509819      0.505001
12          13     0.512898      0.512283      0.495068
13          14     0.508474      0.500077      0.507811
14          15     0.390252      0.386806      0.388967
15          16     0.435342      0.433643      0.436913
16          17     0.447273      0.452716      0.451537
17          18     0.437290      0.438093      0.437008